### ISSUE TITLE
Grafana Dashboards

### ISSUE THREAD

**Issue by Trickx** [SBorg2014/WLAN-Wetterstation#8]
@SBorg2014: very nice Grafana dashboards.
Would you mind sharing it with us?
Especially, I'm interested in your visualisation for windspeed and direction.

**Comment by SBorg2014** [comment]
I think so, but give me some days, because the main part from the Dashboard isn't from me. I have to ask (crunchip from ioBroker-Forum) bevor i can publish it.
"Windrichtung" is a simple "Single Stat" - Dashboard (JSON export follows below) with a mapping of 45° and the arrows are only ASCII-HTML .
I dont't know if you exactly mean this, but the other one is a Dashboard called ["WindRose"](https://grafana.com/grafana/plugins/fatcloud-windrose-panel)

`{
  "cacheTimeout": null,
  "colorBackground": false,
  "colorValue": false,
  "colors": [
    "#299c46",
    "rgba(237, 129, 40, 0.89)",
    "#d44a3a"
  ],
  "datasource": "___DB-Name___",
  "fieldConfig": {
    "defaults": {
      "custom": {}
    },
    "overrides": []
  },
  "format": "short",
  "gauge": {
    "maxValue": 100,
    "minValue": 0,
    "show": false,
    "thresholdLabels": false,
    "thresholdMarkers": true
  },
  "gridPos": {
    "h": 3,
    "w": 2,
    "x": 16,
    "y": 5
  },
  "id": 26,
  "interval": null,
  "links": [],
  "mappingType": 2,
  "mappingTypes": [
    {
      "$$hashKey": "object:1328",
      "name": "value to text",
      "value": 1
    },
    {
      "$$hashKey": "object:1329",
      "name": "range to text",
      "value": 2
    }
  ],
  "maxDataPoints": 100,
  "nullPointMode": "connected",
  "nullText": null,
  "postfix": "",
  "postfixFontSize": "50%",
  "prefix": "",
  "prefixFontSize": "50%",
  "rangeMaps": [
    {
      "$$hashKey": "object:1331",
      "from": "0",
      "text": "&#x21d1;",
      "to": "22.5"
    },
    {
      "$$hashKey": "object:1332",
      "from": "22.5",
      "text": "&#x21d7;",
      "to": "77.5"
    },
    {
      "$$hashKey": "object:1333",
      "from": "77.5",
      "text": "&#x21d2;",
      "to": "112.5"
    },
    {
      "$$hashKey": "object:1334",
      "from": "112.5",
      "text": "&#x21d8;",
      "to": "157.5"
    },
    {
      "$$hashKey": "object:1335",
      "from": "157.5",
      "text": "&#x21d3;",
      "to": "202.5"
    },
    {
      "$$hashKey": "object:1336",
      "from": "202.5",
      "text": "&#x21d9;",
      "to": "247.5"
    },
    {
      "$$hashKey": "object:1337",
      "from": "247.5",
      "text": "&#x21d0;",
      "to": "292.5"
    },
    {
      "$$hashKey": "object:1338",
      "from": "292.5",
      "text": "&#x21d6;",
      "to": "337.5"
    },
    {
      "$$hashKey": "object:1339",
      "from": "337.5",
      "text": "&#x21d1;",
      "to": "360"
    }
  ],
  "sparkline": {
    "fillColor": "rgba(31, 118, 189, 0.18)",
    "full": false,
    "lineColor": "rgb(31, 120, 193)",
    "show": false,
    "ymax": null,
    "ymin": null
  },
  "tableColumn": "",
  "targets": [
    {
      "alias": "Windrichtung",
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "measurement": "javascript.0.Wetterstation.Windrichtung",
      "orderByTime": "ASC",
      "policy": "default",
      "refId": "A",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "value"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "mean"
          }
        ]
      ],
      "tags": []
    }
  ],
  "thresholds": "",
  "timeFrom": null,
  "timeShift": null,
  "title": "Windrichtung",
  "transparent": true,
  "type": "singlestat",
  "valueFontSize": "150%",
  "valueMaps": [
    {
      "op": "=",
      "text": "N/A",
      "value": "null"
    }
  ],
  "valueName": "current"
}`

**Comment by SBorg2014** [comment]
Done :)
https://github.com/SBorg2014/WLAN-Wetterstation/tree/master/Grafana%20Dashboard

**Comment by Trickx** [comment]
Thank you!
